### ISSUE TITLE
I wonder why jsenv-node-module-import-map appears as dependent of my lume repo

### ISSUE THREAD

**Issue by trusktr** [jsenv/jsenv-node-module-import-map#34]
Over at

https://github.com/lume/lume/network/dependents

it appears to show `jsenv-node-module-import-map` as a dependent of `lume`. I wonder why that is. I don't think `jsenv-node-module-import-map` uses `lume`, right?

**Comment by dmail** [comment]
Nope it does not use `lume`.
I have no idea why GitHub thinks there is a dependent relationship 🤷‍♂️ .

**Comment by dmail** [comment]
Oh I know, it's because of https://github.com/jsenv/jsenv-node-module-import-map/blob/02dcc139c94fdf7775c6bf9678643830a35c0f57/test/getImportMapFromProjectFiles/core/issue-20/root/package.json#L4
